title: 日本Symfonyユーザー会
description: 日本Symfonyユーザー会は、PHP製Webアプリケーションフレームワーク「Symfony」の日本におけるユーザーコミュニティです。Symfonyに関する情報の発信や勉強会の開催などを通して、これからSymfonyを導入しようと考えている人/企業、Symfonyをもっと深く学びたいと考えている人/企業、Symfonyの活用でつまずいている人/企業をサポートし、日本におけるSymfonyの活用を促進することを目的として活動しています。

# Url
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://symfony-japan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#url: "http://localhost:4000" # for dev
permalink: pretty

# Social
social:
  twitter: symfony_japan
  facebook: SymfonyJapan
  github: symfony-japan
  connpass: symfony

# SEO
# @see https://github.com/jekyll/jekyll-seo-tag
logo: https://avatars.githubusercontent.com/u/34024636
lang: ja_JP
twitter:
  username: symfony_japan
defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/34024636

google_analytics: UA-28477336-8

include:
  - _pages

markdown: kramdown
kramdown:
  input: GFM

# Plugins
# @see https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Timezone
timezone: Asia/Tokyo

# Encoding
encoding: utf-8

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - LICENSE
  - README.md
  - _posts/drafts
